CREATE TABLE "User" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "name" VARCHAR(255),
    "email" VARCHAR(255) UNIQUE NOT NULL
);

CREATE TABLE "UserRole" (
    "id" BIGSERIAL PRIMARY KEY NOT NULL,
    "userId" BIGSERIAL NOT NULL,
    "role" INTEGER NOT NULL,
    FOREIGN KEY ("userId") REFERENCES "User"("id")
);



